# Generated by Django 5.0.14 on 2026-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='clicks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]